# Generated by Django 3.1.4 on 2021-03-27 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='transcript')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/TeacherProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/StudentProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeraldWeb.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeraldWeb.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeraldWeb.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 21, 42, 158252))),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeraldWeb.student')),
            ],
        ),
    ]
