# Generated by Django 3.1.4 on 2021-03-27 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeraldWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 16516)),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 16516)),
        ),
        migrations.AlterField(
            model_name='feedbackteacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 32140)),
        ),
        migrations.AlterField(
            model_name='feedbackteacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 32140)),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 32140)),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 32140)),
        ),
        migrations.AlterField(
            model_name='notificationteacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 32140)),
        ),
        migrations.AlterField(
            model_name='notificationteacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 32140)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 16516)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 39, 39, 16516)),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='picture',
            field=models.FileField(upload_to='transcript/pdf'),
        ),
    ]
