# Generated by Django 3.1.7 on 2021-05-06 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeraldWeb', '0003_auto_20210403_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 531832)),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 531832)),
        ),
        migrations.AlterField(
            model_name='feedbackteacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 532827)),
        ),
        migrations.AlterField(
            model_name='feedbackteacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 532827)),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 532827)),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 532827)),
        ),
        migrations.AlterField(
            model_name='notificationteacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 533825)),
        ),
        migrations.AlterField(
            model_name='notificationteacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 533825)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 530835)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 9, 21, 52, 530835)),
        ),
    ]
