# Generated by Django 3.1.7 on 2021-05-09 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeraldWeb', '0004_auto_20210506_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 191759)),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 191759)),
        ),
        migrations.AlterField(
            model_name='feedbackteacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 191759)),
        ),
        migrations.AlterField(
            model_name='feedbackteacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 191759)),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 191759)),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 191759)),
        ),
        migrations.AlterField(
            model_name='notificationteacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 192757)),
        ),
        migrations.AlterField(
            model_name='notificationteacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 192757)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 189765)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 23, 18, 189765)),
        ),
    ]
